### ISSUE TITLE
Ping bug

### ISSUE THREAD

**Issue by KenxinKun** [fspcons/ports-service#8]
I noticed a working ping endpoint which is indeed useful when deploying to check the service status. However, I noticed that the service logs a 404 error every time it gets pinged on that endpoint.

How would you fix this bug?

**Comment by fspcons** [comment]
Turns out it had the same root cause as the other issues posted. I had a couple of mapping mistakes on the [docker-compose file](https://github.com/fspcons/ports-service/pull/9/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3) and on the [Dockerfile](https://github.com/fspcons/ports-service/pull/9/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557). 

If you checkout from the [review fixes branch](https://github.com/fspcons/ports-service/tree/5-json-loader-bug) and run the project again it should work as intended 👍

**Comment by KenxinKun** [comment]
Is that the right branch with the 404 fix for the ping? I can see other fixes in the branch though :)

![Screenshot 2023-01-04 at 23 28 24](https://user-images.githubusercontent.com/16479107/210669166-cfd45db6-c32c-471d-8e43-bc74274214d5.png)

**Comment by fspcons** [comment]
Well, that's weird. It's currently working for me:
![image](https://user-images.githubusercontent.com/36037744/210670988-64e0f4bd-d193-41db-bd3a-c0197c143fc2.png)
![image](https://user-images.githubusercontent.com/36037744/210671069-0f122e91-ef03-467e-8e54-50785bb12cc6.png)

May I suggest running the container after a **prune** and with **--force-recreate**? 
It might have the cached image there, so it's working as before the branch pull

**Comment by KenxinKun** [comment]
Oh it works on the browser, but if you look in the container logs it gives me the 404 for some reason 🤷 I wonder if the swagger handlers are recieving the request and not returning immediately after the ping. In any case it seems like an edge case, no need to spend more time on it
